spring:
  application:
    name: concurrency-benchmark

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}